// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.6.1
// source: weather.proto

package weather

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float32                `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float32                `protobuf:"fixed32,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Pressure      float32                `protobuf:"fixed32,3,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherData) Reset() {
	*x = WeatherData{}
	mi := &file_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherData) ProtoMessage() {}

func (x *WeatherData) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherData.ProtoReflect.Descriptor instead.
func (*WeatherData) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherData) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *WeatherData) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherData) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *WeatherData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type WeatherStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvgTemperature float32                `protobuf:"fixed32,1,opt,name=avg_temperature,json=avgTemperature,proto3" json:"avg_temperature,omitempty"`
	AvgHumidity    float32                `protobuf:"fixed32,2,opt,name=avg_humidity,json=avgHumidity,proto3" json:"avg_humidity,omitempty"`
	AvgPressure    float32                `protobuf:"fixed32,3,opt,name=avg_pressure,json=avgPressure,proto3" json:"avg_pressure,omitempty"`
	SamplesCount   int64                  `protobuf:"varint,4,opt,name=samples_count,json=samplesCount,proto3" json:"samples_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WeatherStats) Reset() {
	*x = WeatherStats{}
	mi := &file_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherStats) ProtoMessage() {}

func (x *WeatherStats) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherStats.ProtoReflect.Descriptor instead.
func (*WeatherStats) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{1}
}

func (x *WeatherStats) GetAvgTemperature() float32 {
	if x != nil {
		return x.AvgTemperature
	}
	return 0
}

func (x *WeatherStats) GetAvgHumidity() float32 {
	if x != nil {
		return x.AvgHumidity
	}
	return 0
}

func (x *WeatherStats) GetAvgPressure() float32 {
	if x != nil {
		return x.AvgPressure
	}
	return 0
}

func (x *WeatherStats) GetSamplesCount() int64 {
	if x != nil {
		return x.SamplesCount
	}
	return 0
}

type AlertMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertMessage) Reset() {
	*x = AlertMessage{}
	mi := &file_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertMessage) ProtoMessage() {}

func (x *AlertMessage) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertMessage.ProtoReflect.Descriptor instead.
func (*AlertMessage) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{2}
}

func (x *AlertMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlertMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuthMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMetadata) Reset() {
	*x = AuthMetadata{}
	mi := &file_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMetadata) ProtoMessage() {}

func (x *AuthMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMetadata.ProtoReflect.Descriptor instead.
func (*AuthMetadata) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{3}
}

func (x *AuthMetadata) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_weather_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{4}
}

var File_weather_proto protoreflect.FileDescriptor

const file_weather_proto_rawDesc = "" +
	"\n" +
	"\rweather.proto\x12\aweather\"\x85\x01\n" +
	"\vWeatherData\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x02 \x01(\x02R\bhumidity\x12\x1a\n" +
	"\bpressure\x18\x03 \x01(\x02R\bpressure\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xa2\x01\n" +
	"\fWeatherStats\x12'\n" +
	"\x0favg_temperature\x18\x01 \x01(\x02R\x0eavgTemperature\x12!\n" +
	"\favg_humidity\x18\x02 \x01(\x02R\vavgHumidity\x12!\n" +
	"\favg_pressure\x18\x03 \x01(\x02R\vavgPressure\x12#\n" +
	"\rsamples_count\x18\x04 \x01(\x03R\fsamplesCount\"<\n" +
	"\fAlertMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\fAuthMetadata\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\a\n" +
	"\x05Empty2Z\n" +
	"\x14WeatherSensorService\x12B\n" +
	"\x11StreamWeatherData\x12\x14.weather.WeatherData\x1a\x15.weather.WeatherStats(\x012\xcb\x01\n" +
	"\x10AnalyticsService\x12C\n" +
	"\x12CollectWeatherData\x12\x14.weather.WeatherData\x1a\x15.weather.WeatherStats(\x01\x12:\n" +
	"\x0fStreamAnalytics\x12\x0e.weather.Empty\x1a\x15.weather.WeatherStats0\x01\x126\n" +
	"\rGetLastReport\x12\x0e.weather.Empty\x1a\x15.weather.WeatherStats2\x89\x01\n" +
	"\x10DashboardService\x12=\n" +
	"\x12ReceiveLiveUpdates\x12\x0e.weather.Empty\x1a\x15.weather.WeatherStats0\x01\x126\n" +
	"\rRequestReport\x12\x0e.weather.Empty\x1a\x15.weather.WeatherStatsBV\n" +
	"\x13org.example.weatherB\x11WeatherOuterClassZ,github.com/ismail/weatherapp/weather;weatherb\x06proto3"

var (
	file_weather_proto_rawDescOnce sync.Once
	file_weather_proto_rawDescData []byte
)

func file_weather_proto_rawDescGZIP() []byte {
	file_weather_proto_rawDescOnce.Do(func() {
		file_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)))
	})
	return file_weather_proto_rawDescData
}

var file_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_weather_proto_goTypes = []any{
	(*WeatherData)(nil),  // 0: weather.WeatherData
	(*WeatherStats)(nil), // 1: weather.WeatherStats
	(*AlertMessage)(nil), // 2: weather.AlertMessage
	(*AuthMetadata)(nil), // 3: weather.AuthMetadata
	(*Empty)(nil),        // 4: weather.Empty
}
var file_weather_proto_depIdxs = []int32{
	0, // 0: weather.WeatherSensorService.StreamWeatherData:input_type -> weather.WeatherData
	0, // 1: weather.AnalyticsService.CollectWeatherData:input_type -> weather.WeatherData
	4, // 2: weather.AnalyticsService.StreamAnalytics:input_type -> weather.Empty
	4, // 3: weather.AnalyticsService.GetLastReport:input_type -> weather.Empty
	4, // 4: weather.DashboardService.ReceiveLiveUpdates:input_type -> weather.Empty
	4, // 5: weather.DashboardService.RequestReport:input_type -> weather.Empty
	1, // 6: weather.WeatherSensorService.StreamWeatherData:output_type -> weather.WeatherStats
	1, // 7: weather.AnalyticsService.CollectWeatherData:output_type -> weather.WeatherStats
	1, // 8: weather.AnalyticsService.StreamAnalytics:output_type -> weather.WeatherStats
	1, // 9: weather.AnalyticsService.GetLastReport:output_type -> weather.WeatherStats
	1, // 10: weather.DashboardService.ReceiveLiveUpdates:output_type -> weather.WeatherStats
	1, // 11: weather.DashboardService.RequestReport:output_type -> weather.WeatherStats
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weather_proto_init() }
func file_weather_proto_init() {
	if File_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_weather_proto_goTypes,
		DependencyIndexes: file_weather_proto_depIdxs,
		MessageInfos:      file_weather_proto_msgTypes,
	}.Build()
	File_weather_proto = out.File
	file_weather_proto_goTypes = nil
	file_weather_proto_depIdxs = nil
}
