// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: weather.proto

package weather

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeatherSensorService_StreamWeatherData_FullMethodName = "/weather.WeatherSensorService/StreamWeatherData"
)

// WeatherSensorServiceClient is the client API for WeatherSensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherSensorServiceClient interface {
	StreamWeatherData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WeatherData, WeatherStats], error)
}

type weatherSensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherSensorServiceClient(cc grpc.ClientConnInterface) WeatherSensorServiceClient {
	return &weatherSensorServiceClient{cc}
}

func (c *weatherSensorServiceClient) StreamWeatherData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WeatherData, WeatherStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WeatherSensorService_ServiceDesc.Streams[0], WeatherSensorService_StreamWeatherData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WeatherData, WeatherStats]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WeatherSensorService_StreamWeatherDataClient = grpc.ClientStreamingClient[WeatherData, WeatherStats]

// WeatherSensorServiceServer is the server API for WeatherSensorService service.
// All implementations must embed UnimplementedWeatherSensorServiceServer
// for forward compatibility.
type WeatherSensorServiceServer interface {
	StreamWeatherData(grpc.ClientStreamingServer[WeatherData, WeatherStats]) error
	mustEmbedUnimplementedWeatherSensorServiceServer()
}

// UnimplementedWeatherSensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeatherSensorServiceServer struct{}

func (UnimplementedWeatherSensorServiceServer) StreamWeatherData(grpc.ClientStreamingServer[WeatherData, WeatherStats]) error {
	return status.Errorf(codes.Unimplemented, "method StreamWeatherData not implemented")
}
func (UnimplementedWeatherSensorServiceServer) mustEmbedUnimplementedWeatherSensorServiceServer() {}
func (UnimplementedWeatherSensorServiceServer) testEmbeddedByValue()                              {}

// UnsafeWeatherSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherSensorServiceServer will
// result in compilation errors.
type UnsafeWeatherSensorServiceServer interface {
	mustEmbedUnimplementedWeatherSensorServiceServer()
}

func RegisterWeatherSensorServiceServer(s grpc.ServiceRegistrar, srv WeatherSensorServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeatherSensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeatherSensorService_ServiceDesc, srv)
}

func _WeatherSensorService_StreamWeatherData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WeatherSensorServiceServer).StreamWeatherData(&grpc.GenericServerStream[WeatherData, WeatherStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WeatherSensorService_StreamWeatherDataServer = grpc.ClientStreamingServer[WeatherData, WeatherStats]

// WeatherSensorService_ServiceDesc is the grpc.ServiceDesc for WeatherSensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherSensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weather.WeatherSensorService",
	HandlerType: (*WeatherSensorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWeatherData",
			Handler:       _WeatherSensorService_StreamWeatherData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "weather.proto",
}

const (
	AnalyticsService_CollectWeatherData_FullMethodName = "/weather.AnalyticsService/CollectWeatherData"
	AnalyticsService_StreamAnalytics_FullMethodName    = "/weather.AnalyticsService/StreamAnalytics"
	AnalyticsService_GetLastReport_FullMethodName      = "/weather.AnalyticsService/GetLastReport"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	CollectWeatherData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WeatherData, WeatherStats], error)
	StreamAnalytics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WeatherStats], error)
	GetLastReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WeatherStats, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) CollectWeatherData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WeatherData, WeatherStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalyticsService_ServiceDesc.Streams[0], AnalyticsService_CollectWeatherData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WeatherData, WeatherStats]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_CollectWeatherDataClient = grpc.ClientStreamingClient[WeatherData, WeatherStats]

func (c *analyticsServiceClient) StreamAnalytics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WeatherStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalyticsService_ServiceDesc.Streams[1], AnalyticsService_StreamAnalytics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, WeatherStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_StreamAnalyticsClient = grpc.ServerStreamingClient[WeatherStats]

func (c *analyticsServiceClient) GetLastReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WeatherStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeatherStats)
	err := c.cc.Invoke(ctx, AnalyticsService_GetLastReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	CollectWeatherData(grpc.ClientStreamingServer[WeatherData, WeatherStats]) error
	StreamAnalytics(*Empty, grpc.ServerStreamingServer[WeatherStats]) error
	GetLastReport(context.Context, *Empty) (*WeatherStats, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) CollectWeatherData(grpc.ClientStreamingServer[WeatherData, WeatherStats]) error {
	return status.Errorf(codes.Unimplemented, "method CollectWeatherData not implemented")
}
func (UnimplementedAnalyticsServiceServer) StreamAnalytics(*Empty, grpc.ServerStreamingServer[WeatherStats]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetLastReport(context.Context, *Empty) (*WeatherStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastReport not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_CollectWeatherData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalyticsServiceServer).CollectWeatherData(&grpc.GenericServerStream[WeatherData, WeatherStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_CollectWeatherDataServer = grpc.ClientStreamingServer[WeatherData, WeatherStats]

func _AnalyticsService_StreamAnalytics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalyticsServiceServer).StreamAnalytics(m, &grpc.GenericServerStream[Empty, WeatherStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_StreamAnalyticsServer = grpc.ServerStreamingServer[WeatherStats]

func _AnalyticsService_GetLastReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetLastReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetLastReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetLastReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weather.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastReport",
			Handler:    _AnalyticsService_GetLastReport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectWeatherData",
			Handler:       _AnalyticsService_CollectWeatherData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamAnalytics",
			Handler:       _AnalyticsService_StreamAnalytics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "weather.proto",
}

const (
	DashboardService_ReceiveLiveUpdates_FullMethodName = "/weather.DashboardService/ReceiveLiveUpdates"
	DashboardService_RequestReport_FullMethodName      = "/weather.DashboardService/RequestReport"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	ReceiveLiveUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WeatherStats], error)
	RequestReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WeatherStats, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) ReceiveLiveUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WeatherStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DashboardService_ServiceDesc.Streams[0], DashboardService_ReceiveLiveUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, WeatherStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DashboardService_ReceiveLiveUpdatesClient = grpc.ServerStreamingClient[WeatherStats]

func (c *dashboardServiceClient) RequestReport(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WeatherStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeatherStats)
	err := c.cc.Invoke(ctx, DashboardService_RequestReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
type DashboardServiceServer interface {
	ReceiveLiveUpdates(*Empty, grpc.ServerStreamingServer[WeatherStats]) error
	RequestReport(context.Context, *Empty) (*WeatherStats, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) ReceiveLiveUpdates(*Empty, grpc.ServerStreamingServer[WeatherStats]) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveLiveUpdates not implemented")
}
func (UnimplementedDashboardServiceServer) RequestReport(context.Context, *Empty) (*WeatherStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestReport not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call pancis, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_ReceiveLiveUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DashboardServiceServer).ReceiveLiveUpdates(m, &grpc.GenericServerStream[Empty, WeatherStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DashboardService_ReceiveLiveUpdatesServer = grpc.ServerStreamingServer[WeatherStats]

func _DashboardService_RequestReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).RequestReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_RequestReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).RequestReport(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weather.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestReport",
			Handler:    _DashboardService_RequestReport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveLiveUpdates",
			Handler:       _DashboardService_ReceiveLiveUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "weather.proto",
}
